apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-service
  labels:
    app: edge-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-service
  template:
    metadata:
      labels:
        app: edge-service
    spec:
      imagePullSecrets:
        - name: docker-secret
      containers:
      - name: edge-service
        image: ghcr.io/zzzang12-cns/edge-service
        lifecycle:
          preStop:
            exec:
              command: [ "sh", "-c", "sleep 5" ]
        ports:
        - containerPort: 9000
        env:
        - name: CATALOG_SERVICE_URL
          value: http://catalog-service.default.svc.cluster.local
        - name: ORDER_SERVICE_URL
          value: http://order-service.default.svc.cluster.local
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://config-service.default.svc.cluster.local
        - name: SPRING_REDIS_HOST
          value: polar-redis.default.svc.cluster.local